# Generated by Django 4.2.3 on 2023-10-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_transportation_e_waybills_e_waybill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
