# Generated by Django 4.2.3 on 2023-10-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_e_waybill_item_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_waybills',
            name='transacion_subtype',
        ),
    ]
