# Generated by Django 4.2.3 on 2023-10-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_e_waybills_transacion_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_waybills',
            name='transaction_hsn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='e_waybills',
            name='transaction_subtype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='e_waybills',
            name='transaction_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], max_length=150, null=True),
        ),
    ]
