# Generated by Django 4.2.3 on 2023-10-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_e_waybills_transaction_subtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_waybills',
            old_name='transacion_subtype',
            new_name='transaction_subtype',
        ),
    ]
