# Generated by Django 4.2.3 on 2023-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_bankings_g_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved'), ('Invoiced', 'Invoiced')], max_length=150),
        ),
    ]
