# Generated by Django 4.2.3 on 2023-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_transaction_subtype_e_waybills_transacion_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_waybills',
            name='transacion_subtype',
        ),
        migrations.AddField(
            model_name='e_waybills',
            name='transaction_subtype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
