# Generated by Django 4.2.3 on 2023-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_challan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='is_converted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], default='Draft', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150),
        ),
    ]
