# Generated by Django 4.2.3 on 2023-10-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_e_waybills_transacion_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_waybill_item',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.e_waybills'),
        ),
    ]
