# Generated by Django 4.2.3 on 2023-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_e_waybill_item_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_waybills',
            name='transaction_hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
