# Generated by Django 4.2.3 on 2023-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_challan_is_converted_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(null=True),
        ),
    ]
