# Generated by Django 4.2.3 on 2023-10-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_e_waybills_transaction_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_waybills',
            name='transaction_hsn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='e_waybills',
            name='transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.transportation'),
        ),
    ]
