# Generated by Django 4.2.3 on 2023-10-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_e_waybills_transaction_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_waybills',
            name='cust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
    ]
