# Generated by Django 4.2.3 on 2023-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_deletedchallan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitems',
            name='invtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
