# Generated by Django 4.2.3 on 2023-11-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_payment_bankacc_payment_cheq_id_payment_creditcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentitems',
            name='invid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
