# Generated by Django 4.2.3 on 2023-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_paymentitems_invid'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoices',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
